### ISSUE TITLE
/coa/sys/ueditor/exec后台调通之后，前台仍然显示后端配置项没有正常加载

### ISSUE THREAD

**Issue by woodThunder** [coderliguoqing/ueditor-web#1]
这是我的配置：
UEDITOR_HOME_URL: URL
// 服务器统一请求接口路径
 , serverUrl: "http://10.10.xx.xxx:8081/coa/sys/ueditor/exec"
请问是什么原因呢？域名存在跨域的

**Comment by coderliguoqing** [comment]
> 这是我的配置：
> UEDITOR_HOME_URL: URL
> // 服务器统一请求接口路径
> , serverUrl: "http://10.10.xx.xxx:8081/coa/sys/ueditor/exec"
> 请问是什么原因呢？域名存在跨域的

请你关注接口 ？action=config的情况下，参数的返回格式，以及在F12的调试情况下，js是否存在报错；

**Comment by coderliguoqing** [comment]
> 是不是因为跨域导致的呢?

我上面的回复，提到两个点你要关注啊，一个是返回的参数格式问题；
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Connection: keep-alive
Content-Encoding: gzip
Content-Type: text/plain;charset=UTF-8
Date: Wed, 02 Jan 2019 08:29:27 GMT
Expires: 0
Pragma: no-cache
Server: nginx
Transfer-Encoding: chunked
Vary: Accept-Encoding
X-Application-Context: application
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block

注意是text/plain
第二个问题，F12打开浏览器调试器，JS有没有报错，麻烦你在QQ群里提问，这里我将不再解答！
